[package]
name = "horimetro_server"
version = "0.1.0"
authors = ["Diego Rubin <rubin.diego@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.2"
dbus = "0.6.4"
serde = "1.0.89"
serde_derive = "1.0.89"
sled = "0.19.0"
